[theme]
primaryColor = "#d33682"

backgroundColor = "#001F3F"

secondaryBackgroundColor = "#586e75"

textColor = "#fff"

[client]
toolbarMode = "minimal"
showFooter = false

[server]
enableStaticServing = false
